spring:
  application:
    name: TodoStefanini
  datasource:
    url: ${DS_URL}
    username: ${DS_USERNAME}
    password: ${DS_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
server:
  port: ${PORT:8080}