spring:
  application:
    name: TodoStefanini
  datasource:
    url: ${DS_URL:jdbc:sqlserver://localhost:1433;databaseName=work_todo_db;encrypt=true;trustServerCertificate=true;}
    username: ${DS_USERNAME}
    password: ${DS_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

